- scripts-2.0/components/TaskPicker/styles.scss
[TCD-1483](https://timecampdev.atlassian.net/browse/TCD-1483)
> [TCD-1483] removed padding from recently used and added scroll for taskpicker

- scripts-2.0/ApiService.js
- scripts-2.0/background.js
[TCD-1504](https://timecampdev.atlassian.net/browse/TCD-1504)
> [TCD-1504] Fix

- _locales/en/messages.json
- package.json
- scripts-2.0/background.js
[TCD-1510](https://timecampdev.atlassian.net/browse/TCD-1510)
> [TCD-1510] Form on uninstall and changed name

- package.json
- scripts-2.0/background.js
[TCD-1656](https://timecampdev.atlassian.net/browse/TCD-1656)
> [TCD-1656] Show instruction page after install or update to 2.21.1

- package.json
- scripts-2.0/components/ContextMenu/index.tsx
- scripts-2.0/components/TimeSelectors/index.tsx
- scripts-2.0/helpers/DateTime.js
[TCD-3174](https://timecampdev.atlassian.net/browse/TCD-3174)
[TCD-3140](https://timecampdev.atlassian.net/browse/TCD-3140)
> [TCD-3174] [TCD-3140] Start time field updating

- package-lock.json
- package.json
- scripts-2.0/common.js
**[TCD-2362](https://timecampdev.atlassian.net/browse/TCD-2362)**
> [TCD-2362] Multiple buttons active

- package.json
- scripts/third_party/wrike.js
https://timecampdev.atlassian.net/browse/TCD-3143
> [TCD-3143] Fix show timer for settings bar

- package-lock.json
- package.json
- scripts-2.0/GroupSetting.js
- scripts-2.0/background.js
- scripts-2.0/components/ContextMenu/index.tsx
**[TCD-3485](https://timecampdev.atlassian.net/browse/TCD-3485)**
> [TCD-3485] Time format handling

- package-lock.json
- package.json
- scripts-2.0/components/Note/styles.scss
- scripts-2.0/style/monday.scss
- scripts-2.0/third_party/asana.js
- scripts-2.0/third_party/monday.js
**[TCD-3817](https://timecampdev.atlassian.net/browse/TCD-3817)**
**[TCD-3813](https://timecampdev.atlassian.net/browse/TCD-3813)**
> [TCD-3817] [TCD-3813] Monday and asana fix

- package-lock.json
- package.json
- scripts-2.0/components/TagPicker/index.tsx
[**TCD-2688**](https://timecampdev.atlassian.net/browse/TCD-2688)
> [TCD-2688] Tag filter search by lowercase

- package-lock.json
- package.json
- scripts-2.0/StringExtensions.tsx
- scripts-2.0/common.js
- scripts-2.0/components/TagPicker/index.tsx
- scripts-2.0/components/TaskPicker/index.tsx
- scripts-2.0/popup.js
**[TCD-3854](https://timecampdev.atlassian.net/browse/TCD-3854)**
> [TCD-3853] Diacritics in pickers

- package-lock.json
- package.json
- scripts-2.0/Translator.js
- scripts-2.0/components/Note/styles.scss
- scripts-2.0/components/common/TimePicker/styles.scss
- scripts-2.0/style/main.scss
- scripts-2.0/style/reset-styles.scss
[TCD-3485](https://timecampdev.atlassian.net/browse/TCD-3485)
> [TCD-3485] Styles isolation

- package.json
- scripts/TimerBase.js
- webpack.config.js
[BP-50](https://timecampdev.atlassian.net/browse/BP-50)
> Fix bp 50 chrome plugin plugin doesnt work on hey space

- package-lock.json
- package.json
- scripts-2.0/components/common/TimePicker/index.tsx
- scripts-2.0/helpers/DateTime.js
**[BP-65](https://timecampdev.atlassian.net/browse/BP-65)**
> [BP-65] Am/pm fix

- package-lock.json
- package.json
- scripts-2.0/third_party/asana.js
https://timecampdev.atlassian.net/browse/TCD-6877
> [TCD-6877] Fix Plugin button is not visible in task on ASANA

- package.json
- scripts-2.0/components/ContextMenu/index.tsx
https://timecampdev.atlassian.net/browse/BP-66
> Enable start timer in past

- package.json
- scripts-2.0/components/common/TimePicker/index.tsx
[BP-86](https://timecampdev.atlassian.net/browse/BP-86)
> [BP-86] Fix 12-hour time selector

- README.md
- scripts-2.0/components/ContextMenu/index.tsx
- scripts-2.0/components/ContextMenu/styles.scss
[BP-80](https://timecampdev.atlassian.net/browse/BP-80)
Dodany scroll jak jest wiadomość o integracji
> [BP-80] Remove popup extended height

- scripts-2.0/style/google-calendar.scss
- scripts-2.0/third_party/google-calendar.js
[BP-93](https://timecampdev.atlassian.net/browse/BP-93)
> [BP-93] Fix timer not showing on google calendar

- scripts-2.0/style/trello.scss
- scripts-2.0/third_party/trello.js
[BP-92](https://timecampdev.atlassian.net/browse/BP-92)
> [BP-92] Fix timer icon not showing on trello board view

- package-lock.json
- package.json
- scripts-2.0/ApiService.js
- scripts-2.0/PathService.js
- scripts-2.0/components/PopupMenu/Footer/index.tsx
- webpack.config.js
[BP-102](https://timecampdev.atlassian.net/browse/BP-102)
> [BP-102] Login from enterprise

- scripts-2.0/ApiService.js
- scripts-2.0/background.js
[BP-102](https://timecampdev.atlassian.net/browse/BP-102)
> [BP-102] Fix for discovery endpoint

- _locales/en/messages.json
- package-lock.json
- package.json
- scripts-2.0/components/TaskPicker/index.tsx
- scripts-2.0/style/smartsheet.scss
- scripts-2.0/third_party/smartsheet.js
**[BP-100](https://timecampdev.atlassian.net/browse/BP-109)**
**[BP-110](https://timecampdev.atlassian.net/browse/BP-110)**
> [BP-109] [BP-110] Smartsheet

- package-lock.json
- package.json
- scripts/TimerBase.js
[TCD-7947](https://timecampdev.atlassian.net/browse/TCD-7947)
> [TCD-7947] Removed DOMNodeInserted

- package.json
- scripts/third_party/clickup.js
[BP-112](https://timecampdev.atlassian.net/browse/BP-112)
> [BP-112] Clickup button fix

- package.json
- scripts-2.0/style/monday.scss
- scripts-2.0/third_party/monday.js
[BP-117](https://timecampdev.atlassian.net/browse/BP-117)
----
> [BP-117] Monday selector fix

- integrationList.json
- package-lock.json
- package.json
- scripts-2.0/common.js
- scripts-2.0/style/linear.scss
- scripts-2.0/style/main.scss
- scripts-2.0/style/odoo.scss
- scripts-2.0/third_party/linear.js
- scripts-2.0/third_party/odoo.js
> [TCD-10085] Odoo fix
